/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davba
 */
public class frm_factura extends javax.swing.JInternalFrame {

    DefaultTableModel m;

    public frm_factura() {
        initComponents();
        PrepararTabla();

        clases.cls_cabecerafactura obj = new clases.cls_cabecerafactura();
        obj.CargarTabla(tabla_ventas);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        btn_nuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_numfac = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        btn_kardex_clientes = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_Cancelar = new javax.swing.JButton();
        jdp_fecha = new org.jdesktop.swingx.JXDatePicker();
        cb_descuento = new javax.swing.JComboBox<>();
        txt_subtotal = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();

        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_ventas);

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btn_nuevo)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn_nuevo)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero Factura:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 32, 85, 25));

        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 69, 85, 24));

        jLabel3.setText("Cedula Cliente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 105, 85, 28));

        jLabel4.setText("Nombre Cliente:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 145, -1, 27));
        jPanel1.add(txt_numfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 33, 126, 24));
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 108, 126, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 147, 126, -1));

        btn_kardex_clientes.setText("Buscar");
        btn_kardex_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kardex_clientesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kardex_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 108, -1, -1));

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 214, -1, -1));

        btn_quitar.setText("Quitar");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 214, -1, -1));

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 242, 860, 238));

        jLabel5.setText("Subtotal:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 509, 65, -1));

        jLabel6.setText("Descuento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 537, 65, -1));

        jLabel7.setText("IVA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 562, 65, -1));

        jLabel8.setText("Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 593, 65, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 618, 65, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 590, -1, -1));

        txt_Cancelar.setText("Cancelar");
        txt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, -1));
        jPanel1.add(jdp_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 69, 126, -1));

        cb_descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cb_descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_descuentoActionPerformed(evt);
            }
        });
        jPanel1.add(cb_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 534, 50, -1));

        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 506, 100, -1));
        jPanel1.add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 534, 100, -1));
        jPanel1.add(txt_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 562, 100, -1));
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 590, 100, -1));

        jTabbedPane1.addTab("Mantenimiento", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrepararTabla() {
        String titulos[] = {"ID", "PRODUCTO", "PVP", "CANTIDAD", "TOTAL"};
        m = new DefaultTableModel(null, titulos);
        tabla_productos.setModel(m);

    }
    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void btn_kardex_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kardex_clientesActionPerformed

        formulario.kardex_clientes kardex = new formulario.kardex_clientes(new javax.swing.JFrame(), true);
        
        kardex.setVisible(true);
        txt_cedula.setText(kardex.getCed_cli());
        txt_nombre.setText(kardex.getNom_cli());


    }//GEN-LAST:event_btn_kardex_clientesActionPerformed


    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed

        formulario.kardex_productos kardex = new formulario.kardex_productos(new javax.swing.JFrame(), true);
        kardex.setVisible(true);

        m = (DefaultTableModel) tabla_productos.getModel();
        // {"ID", "Producto", "PVP", "Cantidad", "Total Línea"
        String fila[] = {String.valueOf(kardex.getId_pro()), kardex.getNom_pro(), String.valueOf(kardex.getPvp_pr()), String.valueOf(kardex.getCant_pro()), String.valueOf(kardex.getPvp_pr() * kardex.getCant_pro())};
        m.addRow(fila);

        mtd_calculos();


    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        try {
            Limpiar();

            clases.cls_conexion obj = new clases.cls_conexion();
            ResultSet rs = obj.Consulta("Select max(num_fac)+1 AS Codigo FROM cabecera_factura");

            while (rs.next()) {
                try {
                    if (rs.getObject("Codigo") == null) {
                        txt_numfac.setText("1");
                    } else {
                        txt_numfac.setText(rs.getObject("Codigo").toString());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frm_factura.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            txt_numfac.enable(false);
            jTabbedPane1.setEnabledAt(0, false);
            jTabbedPane1.setEnabledAt(1, true);
            jTabbedPane1.setSelectedIndex(1);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(frm_factura.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CancelarActionPerformed

        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_txt_CancelarActionPerformed

    private void cb_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_descuentoActionPerformed
        mtd_calculos();
    }//GEN-LAST:event_cb_descuentoActionPerformed

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        try {
            if (tabla_productos.getSelectedRow() >= 0) {
                m = (DefaultTableModel) tabla_productos.getModel();
                m.removeRow(tabla_productos.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un registro");
            }
        } catch (Exception er) {
            javax.swing.JOptionPane.showMessageDialog(null, er.getMessage());
        }

    }//GEN-LAST:event_btn_quitarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        try {
            String error;
            // int num_fac, String fec_fac, String ced_cli, double sub_fac, double des_fac, double iva_fac, double tot_fac
            clases.cls_cabecerafactura obj = new clases.cls_cabecerafactura(Integer.parseInt(txt_numfac.getText()), jdp_fecha.getDate().toLocaleString(), txt_cedula.getText(), Double.parseDouble(txt_subtotal.getText()), Double.parseDouble(txt_descuento.getText()), Double.parseDouble(txt_iva.getText()), Double.parseDouble(txt_total.getText()));
            error = obj.guardar();
            if (!"".equals(error)) {
                JOptionPane.showMessageDialog(null, error, "Sistema Inventario", JOptionPane.ERROR_MESSAGE);
            }
            for (int i = 0; i < tabla_productos.getRowCount(); i++) {
                clases.cls_detallefactura obj_det = new clases.cls_detallefactura(Integer.parseInt(txt_numfac.getText()), Integer.parseInt(tabla_productos.getValueAt(i, 0).toString()), Integer.parseInt(tabla_productos.getValueAt(i, 3).toString()), Double.parseDouble(tabla_productos.getValueAt(i, 4).toString()));
                error = obj_det.guardar();
                if (!"".equals(error)) {
                    JOptionPane.showMessageDialog(null, error, "Sistema Inventario", JOptionPane.ERROR_MESSAGE);
                }
            }
            obj.CargarTabla(tabla_ventas);
        } catch (Exception er) {
            javax.swing.JOptionPane.showMessageDialog(null, er.getMessage());
        }
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_btn_guardarActionPerformed
    
    private void mtd_calculos() {
        double subtotal = 0;
        double descuento = 0;
        double iva;
        double total;

        for (int i = 0; i < tabla_productos.getRowCount(); i++) {
            subtotal = subtotal + Double.parseDouble(tabla_productos.getValueAt(i, 4).toString());
        }
        txt_subtotal.setText(String.valueOf(subtotal));

        descuento = (Double.parseDouble(cb_descuento.getSelectedItem().toString()) * subtotal) / 100;
        txt_descuento.setText(String.valueOf(descuento));

        iva = ((subtotal - descuento) * 14) / 100;
        txt_iva.setText(String.valueOf(iva));

        total = (subtotal - descuento) + iva;
        txt_total.setText(String.valueOf(total));

    }

    public void Limpiar() {
        txt_numfac.setText("");
        txt_cedula.setText("");
        txt_nombre.setText("");
        txt_subtotal.setText("");
        txt_descuento.setText("");
        txt_iva.setText("");
        txt_total.setText("");
        cb_descuento.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_kardex_clientes;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JComboBox<String> cb_descuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXDatePicker jdp_fecha;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTable tabla_ventas;
    private javax.swing.JButton txt_Cancelar;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numfac;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
