/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author davba
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Equipos = new javax.swing.JMenu();
        Menu_Equipos = new javax.swing.JMenuItem();
        menu_clientes = new javax.swing.JMenuItem();
        menu_factura = new javax.swing.JMenuItem();
        menu_productos = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Equipos.setMnemonic('f');
        Equipos.setText("Programas");

        Menu_Equipos.setMnemonic('o');
        Menu_Equipos.setText("Equipos");
        Menu_Equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_EquiposActionPerformed(evt);
            }
        });
        Equipos.add(Menu_Equipos);

        menu_clientes.setMnemonic('s');
        menu_clientes.setText("Clientes");
        menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clientesActionPerformed(evt);
            }
        });
        Equipos.add(menu_clientes);

        menu_factura.setMnemonic('a');
        menu_factura.setText("Factura");
        menu_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_facturaActionPerformed(evt);
            }
        });
        Equipos.add(menu_factura);

        menu_productos.setMnemonic('x');
        menu_productos.setText("Productos");
        menu_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_productosActionPerformed(evt);
            }
        });
        Equipos.add(menu_productos);

        menuBar.add(Equipos);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_productosActionPerformed

        frm_productos Productos = new frm_productos();
        desktopPane.add(Productos);
        Productos.setVisible(true);


    }//GEN-LAST:event_menu_productosActionPerformed

    private void Menu_EquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_EquiposActionPerformed

        frm_equipos Equipos = new frm_equipos();
        desktopPane.add(Equipos);
        Equipos.setVisible(true);

    }//GEN-LAST:event_Menu_EquiposActionPerformed

    private void menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clientesActionPerformed

        frm_clientes Clientes = new frm_clientes();
        desktopPane.add(Clientes);
        Clientes.setVisible(true);

    }//GEN-LAST:event_menu_clientesActionPerformed

    private void menu_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_facturaActionPerformed
        frm_factura Factura = new frm_factura();
        desktopPane.add(Factura);
        Factura.setVisible(true);


    }//GEN-LAST:event_menu_facturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Equipos;
    private javax.swing.JMenuItem Menu_Equipos;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menu_clientes;
    private javax.swing.JMenuItem menu_factura;
    private javax.swing.JMenuItem menu_productos;
    // End of variables declaration//GEN-END:variables

}
